apiVersion: v1
kind: ServiceAccount
metadata:
  name: apex-api-sa
  namespace: apex-banking
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apex-mysql-pvc
  namespace: apex-banking
  labels:
    app: apex-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apex-mysql
  namespace: apex-banking
  labels:
    app: apex-mysql
    tier: database
spec:
  serviceName: apex-mysql
  replicas: 1
  selector:
    matchLabels:
      app: apex-mysql
      tier: database
  template:
    metadata:
      labels:
        app: apex-mysql
        tier: database
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apex-mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: apex_banking
            - name: MYSQL_USER
              value: apex_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apex-mysql-secrets
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: apex-mysql-pvc
        - name: init-sql
          configMap:
            name: apex-mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: apex-mysql
  namespace: apex-banking
  labels:
    app: apex-mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: apex-mysql
    tier: database