apiVersion: v1
kind: Secret
metadata:
  name: apex-api-secrets
  namespace: apex-banking
type: Opaque
stringData:
  DB_USER: apex_user
  DB_PASSWORD: ChangeMe!
  JWT_ACCESS_SECRET: change-this-to-a-random-64-char-string
  JWT_REFRESH_SECRET: change-this-to-another-random-64-char-string
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASS: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: apex-mysql-secrets
  namespace: apex-banking
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass!
  MYSQL_PASSWORD: ChangeMe!